//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.1.7297")]
	public enum BulkDeleteOperation_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceling = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Paused = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pausing = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Retrying = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Waiting = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WaitingForResources = 0,
	}
}