//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.1.7297")]
	public enum DuplicateRuleCondition_OperatorCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExactMatch = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExactMatch_PickListLabel = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExactMatch_PickListValue = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SameDate = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SameDateandTime = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SameFirstCharacters = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SameLastCharacters = 2,
	}
}