//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.1.7297")]
	public enum ImportMap_SourceType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GenericMapforContactandAccount = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MapForSalesForcecomContactandAccountReportExport = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MapForSalesForcecomFullDataExport = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MapForSalesForcecomReportExport = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftOfficeOutlook2010withBusinessContactManager = 4,
	}
}