//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.1.7297")]
	public enum Incident_CaseOriginCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 2483,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 3986,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Web = 3,
	}
}