using DLaB.ModelBuilderExtensions.Entity;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom;
using System.Text;

namespace DLaB.ModelBuilderExtensions.Tests
{
    [TestClass]
    public class DateTimeMetadataAttributeGeneratorTests
    {
        [TestMethod]
        public void TestGeneration()
        {
            Assert.AreEqual(Expected, GenerateCode(makeReferenceTypesNullable: false));
        }

        [TestMethod]
        public void TestGenerationNullable()
        {
            Assert.AreEqual(ExpectedNullable, GenerateCode(makeReferenceTypesNullable: true));
        }

        private static string GenerateCode(bool makeReferenceTypesNullable)
        {
            var codeCompileUnit = new CodeCompileUnit();
            var codeNamespace = new CodeNamespace("Test");
            codeCompileUnit.Namespaces.Add(codeNamespace);
            var sut = new DateTimeMetadataAttributeGenerator(makeReferenceTypesNullable);

            sut.CustomizeCodeDom(codeCompileUnit, null);

            var provider = new Microsoft.CSharp.CSharpCodeProvider();
            var stringBuilder = new StringBuilder();
            var stringWriter = new System.IO.StringWriter(stringBuilder);
            provider.GenerateCodeFromCompileUnit(codeCompileUnit, stringWriter, new System.CodeDom.Compiler.CodeGeneratorOptions
            {
                IndentString = "\t"
            });
            return stringBuilder.ToString().Trim();
        }

        const string Expected = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
	
	
	/// <summary>
	/// The format of the DateTime column as defined in Dataverse.
	/// </summary>
	public enum DateTimeFormat {
		
		/// <summary>
		/// The column contains both a date and a time.
		/// </summary>
		DateAndTime = 0,
		
		/// <summary>
		/// The column contains only a date.
		/// </summary>
		DateOnly = 1,
	}
	
	/// <summary>
	/// The time zone adjustment (behavior) of the DateTime column as defined in Dataverse.
	/// </summary>
	public enum DateTimeTimeZoneAdjustment {
		
		/// <summary>
		/// The value is stored in UTC and displayed in the time zone of the user.
		/// </summary>
		UserLocal = 0,
		
		/// <summary>
		/// The value is stored and displayed the same, independent of the time zone of the user.
		/// </summary>
		TimeZoneIndependent = 1,
		
		/// <summary>
		/// The time portion of the value is not stored, and the date is displayed the same, independent of the time zone of the user.
		/// </summary>
		DateOnly = 2,
	}
	
	/// <summary>
	/// Attribute to handle storing the DateTime column's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Property)]
	public sealed class DateTimeMetadataAttribute : System.Attribute {
		
		/// <summary>
		/// Format of the DateTime column.
		/// </summary>
		public DateTimeFormat Format { get; set; }
		/// <summary>
		/// Time zone adjustment (behavior) of the DateTime column.
		/// </summary>
		public DateTimeTimeZoneAdjustment TimeZone { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref=""DateTimeMetadataAttribute""/> class.
		/// </summary>
		/// <param name=""format"">Format of the DateTime column.</param>
		/// <param name=""timeZone"">Time zone adjustment (behavior) of the DateTime column.</param>
		public DateTimeMetadataAttribute(DateTimeFormat format, DateTimeTimeZoneAdjustment timeZone) {
			this.Format = format;
			this.TimeZone = timeZone;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of the DateTimeMetadataAttribute.
	/// </summary>
	public class DateTimeMetadataAttributeExtensions {
		
		/// <summary>
		/// Returns the DateTimeMetadataAttribute of the given DateTime property of the entity.
		/// </summary>
		/// <typeparam name=""T"">Entity Type</typeparam>
		/// <param name=""entity"">Entity containing the DateTime property</param>
		/// <param name=""propertyName"">Name of the DateTime property adorned with a DateTimeMetadataAttribute</param>
		public static DateTimeMetadataAttribute GetMetadata<T>(this T entity, string propertyName)
			where T : Microsoft.Xrm.Sdk.Entity {
			System.Reflection.PropertyInfo property = typeof(T).GetProperty(propertyName);
			if (property == null) {
				throw new System.ArgumentException(""No property named "" + propertyName + "" was found on type "" + typeof(T).FullName + ""!"");
			}
			System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(property, typeof(DateTimeMetadataAttribute));
			if (attribute == null) {
				throw new System.ArgumentException(""Property "" + propertyName + "" of type "" + typeof(T).FullName + "" is not adorned with a DateTimeMetadataAttribute!"");
			}
			return ((DateTimeMetadataAttribute)(attribute));
		}
	}
}";

        const string ExpectedNullable = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
	
	
	/// <summary>
	/// The format of the DateTime column as defined in Dataverse.
	/// </summary>
	public enum DateTimeFormat {
		
		/// <summary>
		/// The column contains both a date and a time.
		/// </summary>
		DateAndTime = 0,
		
		/// <summary>
		/// The column contains only a date.
		/// </summary>
		DateOnly = 1,
	}
	
	/// <summary>
	/// The time zone adjustment (behavior) of the DateTime column as defined in Dataverse.
	/// </summary>
	public enum DateTimeTimeZoneAdjustment {
		
		/// <summary>
		/// The value is stored in UTC and displayed in the time zone of the user.
		/// </summary>
		UserLocal = 0,
		
		/// <summary>
		/// The value is stored and displayed the same, independent of the time zone of the user.
		/// </summary>
		TimeZoneIndependent = 1,
		
		/// <summary>
		/// The time portion of the value is not stored, and the date is displayed the same, independent of the time zone of the user.
		/// </summary>
		DateOnly = 2,
	}
	
	/// <summary>
	/// Attribute to handle storing the DateTime column's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Property)]
	public sealed class DateTimeMetadataAttribute : System.Attribute {
		
		/// <summary>
		/// Format of the DateTime column.
		/// </summary>
		public DateTimeFormat Format { get; set; }
		/// <summary>
		/// Time zone adjustment (behavior) of the DateTime column.
		/// </summary>
		public DateTimeTimeZoneAdjustment TimeZone { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref=""DateTimeMetadataAttribute""/> class.
		/// </summary>
		/// <param name=""format"">Format of the DateTime column.</param>
		/// <param name=""timeZone"">Time zone adjustment (behavior) of the DateTime column.</param>
		public DateTimeMetadataAttribute(DateTimeFormat format, DateTimeTimeZoneAdjustment timeZone) {
			this.Format = format;
			this.TimeZone = timeZone;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of the DateTimeMetadataAttribute.
	/// </summary>
	public class DateTimeMetadataAttributeExtensions {
		
		/// <summary>
		/// Returns the DateTimeMetadataAttribute of the given DateTime property of the entity.
		/// </summary>
		/// <typeparam name=""T"">Entity Type</typeparam>
		/// <param name=""entity"">Entity containing the DateTime property</param>
		/// <param name=""propertyName"">Name of the DateTime property adorned with a DateTimeMetadataAttribute</param>
		public static DateTimeMetadataAttribute GetMetadata<T>(this T entity, string propertyName)
			where T : Microsoft.Xrm.Sdk.Entity {
			System.Reflection.PropertyInfo? property = typeof(T).GetProperty(propertyName);
			if (property == null) {
				throw new System.ArgumentException(""No property named "" + propertyName + "" was found on type "" + typeof(T).FullName + ""!"");
			}
			System.Attribute? attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(property, typeof(DateTimeMetadataAttribute));
			if (attribute == null) {
				throw new System.ArgumentException(""Property "" + propertyName + "" of type "" + typeof(T).FullName + "" is not adorned with a DateTimeMetadataAttribute!"");
			}
			return ((DateTimeMetadataAttribute)(attribute));
		}
	}
}";
    }
}
