//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	/// <summary>
	/// Log used to track bulk operation execution, successes, and failures.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bulkoperationlog")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.1.7297")]
	public partial class BulkOperationLog : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public struct Fields
		{
			public const string AdditionalInfo = "additionalinfo";
			public const string BulkOperationId = "bulkoperationid";
			public const string BulkOperationLogId = "bulkoperationlogid";
			public const string Id = "bulkoperationlogid";
			public const string CreatedObjectId = "createdobjectid";
			public const string ErrorNumber = "errornumber";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningUser = "owninguser";
			public const string RegardingObjectId = "regardingobjectid";
			public const string activity_pointer_BulkOperation_logs = "activity_pointer_BulkOperation_logs";
			public const string BulkOperation_logs = "BulkOperation_logs";
			public const string CreatedAccount_BulkOperationLogs2 = "CreatedAccount_BulkOperationLogs2";
			public const string CreatedActivity_BulkOperationLogs = "CreatedActivity_BulkOperationLogs";
			public const string CreatedContact_BulkOperationLogs = "CreatedContact_BulkOperationLogs";
			public const string CreatedLead_BulkOperationLogs = "CreatedLead_BulkOperationLogs";
			public const string CreatedOpportunity_BulkOperationLogs = "CreatedOpportunity_BulkOperationLogs";
			public const string SourceAccount_BulkOperationLogs = "SourceAccount_BulkOperationLogs";
			public const string SourceContact_BulkOperationLogs = "SourceContact_BulkOperationLogs";
			public const string SourceLead_BulkOperationLogs = "SourceLead_BulkOperationLogs";
		}

		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BulkOperationLog() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bulkoperationlog";
		
		public const int EntityTypeCode = 4405;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Shows the data value at which an error occurred during the quick campaign.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("additionalinfo")]
		public string AdditionalInfo
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("additionalinfo");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("AdditionalInfo");
				this.SetAttributeValue("additionalinfo", value);
				this.OnPropertyChanged("AdditionalInfo");
			}
		}
		
		/// <summary>
		/// Shows the quick campaign record that the log applies to. This information is used to relate log data to the parent quick campaign.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bulkoperationid")]
		public Microsoft.Xrm.Sdk.EntityReference BulkOperationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bulkoperationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BulkOperationId");
				this.SetAttributeValue("bulkoperationid", value);
				this.OnPropertyChanged("BulkOperationId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the bulk operation log.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bulkoperationlogid")]
		public System.Nullable<System.Guid> BulkOperationLogId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bulkoperationlogid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BulkOperationLogId");
				this.SetAttributeValue("bulkoperationlogid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("BulkOperationLogId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bulkoperationlogid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.BulkOperationLogId = value;
			}
		}
		
		/// <summary>
		/// Choose the activity or other item created by the bulk operation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdobjectid")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedObjectId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdobjectid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedObjectId");
				this.SetAttributeValue("createdobjectid", value);
				this.OnPropertyChanged("CreatedObjectId");
			}
		}
		
		/// <summary>
		/// Shows the error code that is used to troubleshoot issues in the bulk operation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("errornumber")]
		public System.Nullable<int> ErrorNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("errornumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the bulk operation log.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit that owns the bulk operation log.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public System.Nullable<System.Guid> OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the bulk operation log.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public System.Nullable<System.Guid> OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Choose the account, contact, lead, or list that the bulk operation log item applies to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		public Microsoft.Xrm.Sdk.EntityReference RegardingObjectId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("regardingobjectid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("RegardingObjectId");
				this.SetAttributeValue("regardingobjectid", value);
				this.OnPropertyChanged("RegardingObjectId");
			}
		}
		
		/// <summary>
		/// 1:N BulkOperationLog_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("BulkOperationLog_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.AsyncOperation> BulkOperationLog_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("BulkOperationLog_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BulkOperationLog_AsyncOperations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("BulkOperationLog_AsyncOperations", null, value);
				this.OnPropertyChanged("BulkOperationLog_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N BulkOperationLog_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("BulkOperationLog_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BulkDeleteFailure> BulkOperationLog_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("BulkOperationLog_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BulkOperationLog_BulkDeleteFailures");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("BulkOperationLog_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("BulkOperationLog_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N userentityinstancedata_bulkoperationlog
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_bulkoperationlog")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.UserEntityInstanceData> userentityinstancedata_bulkoperationlog
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("userentityinstancedata_bulkoperationlog", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("userentityinstancedata_bulkoperationlog");
				this.SetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("userentityinstancedata_bulkoperationlog", null, value);
				this.OnPropertyChanged("userentityinstancedata_bulkoperationlog");
			}
		}
		
		/// <summary>
		/// N:1 activity_pointer_BulkOperation_logs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bulkoperationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("activity_pointer_BulkOperation_logs")]
		public DLaB.Xrm.Entities.ActivityPointer activity_pointer_BulkOperation_logs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.ActivityPointer>("activity_pointer_BulkOperation_logs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("activity_pointer_BulkOperation_logs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.ActivityPointer>("activity_pointer_BulkOperation_logs", null, value);
				this.OnPropertyChanged("activity_pointer_BulkOperation_logs");
			}
		}
		
		/// <summary>
		/// N:1 BulkOperation_logs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bulkoperationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("BulkOperation_logs")]
		public DLaB.Xrm.Entities.BulkOperation BulkOperation_logs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.BulkOperation>("BulkOperation_logs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BulkOperation_logs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.BulkOperation>("BulkOperation_logs", null, value);
				this.OnPropertyChanged("BulkOperation_logs");
			}
		}
		
		/// <summary>
		/// N:1 CreatedAccount_BulkOperationLogs2
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("CreatedAccount_BulkOperationLogs2")]
		public DLaB.Xrm.Entities.Account CreatedAccount_BulkOperationLogs2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Account>("CreatedAccount_BulkOperationLogs2", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedAccount_BulkOperationLogs2");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Account>("CreatedAccount_BulkOperationLogs2", null, value);
				this.OnPropertyChanged("CreatedAccount_BulkOperationLogs2");
			}
		}
		
		/// <summary>
		/// N:1 CreatedActivity_BulkOperationLogs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("CreatedActivity_BulkOperationLogs")]
		public DLaB.Xrm.Entities.ActivityPointer CreatedActivity_BulkOperationLogs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.ActivityPointer>("CreatedActivity_BulkOperationLogs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedActivity_BulkOperationLogs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.ActivityPointer>("CreatedActivity_BulkOperationLogs", null, value);
				this.OnPropertyChanged("CreatedActivity_BulkOperationLogs");
			}
		}
		
		/// <summary>
		/// N:1 CreatedContact_BulkOperationLogs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("CreatedContact_BulkOperationLogs")]
		public DLaB.Xrm.Entities.Contact CreatedContact_BulkOperationLogs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Contact>("CreatedContact_BulkOperationLogs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedContact_BulkOperationLogs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Contact>("CreatedContact_BulkOperationLogs", null, value);
				this.OnPropertyChanged("CreatedContact_BulkOperationLogs");
			}
		}
		
		/// <summary>
		/// N:1 CreatedLead_BulkOperationLogs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("CreatedLead_BulkOperationLogs")]
		public DLaB.Xrm.Entities.Lead CreatedLead_BulkOperationLogs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Lead>("CreatedLead_BulkOperationLogs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedLead_BulkOperationLogs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Lead>("CreatedLead_BulkOperationLogs", null, value);
				this.OnPropertyChanged("CreatedLead_BulkOperationLogs");
			}
		}
		
		/// <summary>
		/// N:1 CreatedOpportunity_BulkOperationLogs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("CreatedOpportunity_BulkOperationLogs")]
		public DLaB.Xrm.Entities.Opportunity CreatedOpportunity_BulkOperationLogs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Opportunity>("CreatedOpportunity_BulkOperationLogs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOpportunity_BulkOperationLogs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Opportunity>("CreatedOpportunity_BulkOperationLogs", null, value);
				this.OnPropertyChanged("CreatedOpportunity_BulkOperationLogs");
			}
		}
		
		/// <summary>
		/// N:1 SourceAccount_BulkOperationLogs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SourceAccount_BulkOperationLogs")]
		public DLaB.Xrm.Entities.Account SourceAccount_BulkOperationLogs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Account>("SourceAccount_BulkOperationLogs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SourceAccount_BulkOperationLogs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Account>("SourceAccount_BulkOperationLogs", null, value);
				this.OnPropertyChanged("SourceAccount_BulkOperationLogs");
			}
		}
		
		/// <summary>
		/// N:1 SourceContact_BulkOperationLogs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SourceContact_BulkOperationLogs")]
		public DLaB.Xrm.Entities.Contact SourceContact_BulkOperationLogs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Contact>("SourceContact_BulkOperationLogs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SourceContact_BulkOperationLogs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Contact>("SourceContact_BulkOperationLogs", null, value);
				this.OnPropertyChanged("SourceContact_BulkOperationLogs");
			}
		}
		
		/// <summary>
		/// N:1 SourceLead_BulkOperationLogs
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SourceLead_BulkOperationLogs")]
		public DLaB.Xrm.Entities.Lead SourceLead_BulkOperationLogs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Lead>("SourceLead_BulkOperationLogs", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SourceLead_BulkOperationLogs");
				this.SetRelatedEntity<DLaB.Xrm.Entities.Lead>("SourceLead_BulkOperationLogs", null, value);
				this.OnPropertyChanged("SourceLead_BulkOperationLogs");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BulkOperationLog(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["bulkoperationlogid"] = base.Id;
                        break;
                    case "bulkoperationlogid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}