//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.Xrm.Entities
{
	
	/// <summary>
	/// Metadata of knowledge base (KB) articles associated with Microsoft Dynamics CRM entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("knowledgebaserecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.1.7297")]
	public partial class KnowledgeBaseRecord : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public struct Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ExchangeRate = "exchangerate";
			public const string KnowledgeBaseRecordId = "knowledgebaserecordid";
			public const string Id = "knowledgebaserecordid";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string PrivateUrl = "privateurl";
			public const string PublicUrl = "publicurl";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string Title = "title";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UniqueId = "uniqueid";
			public const string VersionNumber = "versionnumber";
			public const string lk_KnowledgeBaseRecord_createdby = "lk_KnowledgeBaseRecord_createdby";
			public const string lk_KnowledgeBaseRecord_createdonbehalfby = "lk_KnowledgeBaseRecord_createdonbehalfby";
			public const string lk_KnowledgeBaseRecord_modifiedby = "lk_KnowledgeBaseRecord_modifiedby";
			public const string lk_KnowledgeBaseRecord_modifiedonbehalfby = "lk_KnowledgeBaseRecord_modifiedonbehalfby";
			public const string organization_KnowledgeBaseRecord = "organization_KnowledgeBaseRecord";
			public const string TransactionCurrency_KnowledgeBaseRecord = "TransactionCurrency_KnowledgeBaseRecord";
		}

		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public KnowledgeBaseRecord() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "knowledgebaserecord";
		
		public const int EntityTypeCode = 9930;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the knowledge base record with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// This field will be used to store the Unique ID of the associated Knowledge Base records
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgebaserecordid")]
		public System.Nullable<System.Guid> KnowledgeBaseRecordId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("knowledgebaserecordid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecordId");
				this.SetAttributeValue("knowledgebaserecordid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("KnowledgeBaseRecordId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgebaserecordid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.KnowledgeBaseRecordId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Shows the internal Parature service desk URL of the knowledge base records.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("privateurl")]
		public string PrivateUrl
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("privateurl");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PrivateUrl");
				this.SetAttributeValue("privateurl", value);
				this.OnPropertyChanged("PrivateUrl");
			}
		}
		
		/// <summary>
		/// Shows the public Parature portal URL of the knowledge base records.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publicurl")]
		public string PublicUrl
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("publicurl");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PublicUrl");
				this.SetAttributeValue("publicurl", value);
				this.OnPropertyChanged("PublicUrl");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the title of the knowledge base (KB) Record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
		public string Title
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("title");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Title");
				this.SetAttributeValue("title", value);
				this.OnPropertyChanged("Title");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the Knowledge Base Record with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Shows the unique ID of the linked knowledge base (KB) article.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniqueid")]
		public string UniqueId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("uniqueid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UniqueId");
				this.SetAttributeValue("uniqueid", value);
				this.OnPropertyChanged("UniqueId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ActivityPointer> KnowledgeBaseRecord_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ActivityPointer>("KnowledgeBaseRecord_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_ActivityPointers");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ActivityPointer>("KnowledgeBaseRecord_ActivityPointers", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Annotations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Annotation> KnowledgeBaseRecord_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Annotation>("KnowledgeBaseRecord_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Annotations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Annotation>("KnowledgeBaseRecord_Annotations", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Appointments")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Appointment> KnowledgeBaseRecord_Appointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Appointment>("KnowledgeBaseRecord_Appointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Appointments");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Appointment>("KnowledgeBaseRecord_Appointments", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.AsyncOperation> KnowledgeBaseRecord_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("KnowledgeBaseRecord_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_AsyncOperations");
				this.SetRelatedEntities<DLaB.Xrm.Entities.AsyncOperation>("KnowledgeBaseRecord_AsyncOperations", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.BulkDeleteFailure> KnowledgeBaseRecord_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("KnowledgeBaseRecord_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_BulkDeleteFailures");
				this.SetRelatedEntities<DLaB.Xrm.Entities.BulkDeleteFailure>("KnowledgeBaseRecord_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_connections1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_connections1")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Connection> KnowledgeBaseRecord_connections1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Connection>("KnowledgeBaseRecord_connections1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_connections1");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Connection>("KnowledgeBaseRecord_connections1", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_connections1");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_connections2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_connections2")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Connection> KnowledgeBaseRecord_connections2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Connection>("KnowledgeBaseRecord_connections2", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_connections2");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Connection>("KnowledgeBaseRecord_connections2", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_connections2");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> KnowledgeBaseRecord_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("KnowledgeBaseRecord_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_DuplicateBaseRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("KnowledgeBaseRecord_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.DuplicateRecord> KnowledgeBaseRecord_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("KnowledgeBaseRecord_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_DuplicateMatchingRecord");
				this.SetRelatedEntities<DLaB.Xrm.Entities.DuplicateRecord>("KnowledgeBaseRecord_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Emails")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Email> KnowledgeBaseRecord_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Email>("KnowledgeBaseRecord_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Emails");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Email>("KnowledgeBaseRecord_Emails", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Emails");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Faxes")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Fax> KnowledgeBaseRecord_Faxes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Fax>("KnowledgeBaseRecord_Faxes", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Faxes");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Fax>("KnowledgeBaseRecord_Faxes", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Letters")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Letter> KnowledgeBaseRecord_Letters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Letter>("KnowledgeBaseRecord_Letters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Letters");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Letter>("KnowledgeBaseRecord_Letters", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Letters");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.PhoneCall> KnowledgeBaseRecord_PhoneCalls
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.PhoneCall>("KnowledgeBaseRecord_PhoneCalls", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_PhoneCalls");
				this.SetRelatedEntities<DLaB.Xrm.Entities.PhoneCall>("KnowledgeBaseRecord_PhoneCalls", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_PrincipalObjectAttributeAccess
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_PrincipalObjectAttributeAccess")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess> KnowledgeBaseRecord_PrincipalObjectAttributeAccess
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("KnowledgeBaseRecord_PrincipalObjectAttributeAccess", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_PrincipalObjectAttributeAccess");
				this.SetRelatedEntities<DLaB.Xrm.Entities.PrincipalObjectAttributeAccess>("KnowledgeBaseRecord_PrincipalObjectAttributeAccess", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_PrincipalObjectAttributeAccess");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_ProcessSession")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ProcessSession> KnowledgeBaseRecord_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("KnowledgeBaseRecord_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_ProcessSession");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ProcessSession>("KnowledgeBaseRecord_ProcessSession", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.RecurringAppointmentMaster> KnowledgeBaseRecord_RecurringAppointmentMasters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.RecurringAppointmentMaster>("KnowledgeBaseRecord_RecurringAppointmentMasters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_RecurringAppointmentMasters");
				this.SetRelatedEntities<DLaB.Xrm.Entities.RecurringAppointmentMaster>("KnowledgeBaseRecord_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.ServiceAppointment> KnowledgeBaseRecord_ServiceAppointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.ServiceAppointment>("KnowledgeBaseRecord_ServiceAppointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_ServiceAppointments");
				this.SetRelatedEntities<DLaB.Xrm.Entities.ServiceAppointment>("KnowledgeBaseRecord_ServiceAppointments", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_SocialActivities")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.SocialActivity> KnowledgeBaseRecord_SocialActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.SocialActivity>("KnowledgeBaseRecord_SocialActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_SocialActivities");
				this.SetRelatedEntities<DLaB.Xrm.Entities.SocialActivity>("KnowledgeBaseRecord_SocialActivities", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Tasks")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Task> KnowledgeBaseRecord_Tasks
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Task>("KnowledgeBaseRecord_Tasks", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Tasks");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Task>("KnowledgeBaseRecord_Tasks", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.UserEntityInstanceData> KnowledgeBaseRecord_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("KnowledgeBaseRecord_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_UserEntityInstanceDatas");
				this.SetRelatedEntities<DLaB.Xrm.Entities.UserEntityInstanceData>("KnowledgeBaseRecord_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// N:N KnowledgeBaseRecord_Incident
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Incident")]
		public System.Collections.Generic.IEnumerable<DLaB.Xrm.Entities.Incident> KnowledgeBaseRecord_Incident
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DLaB.Xrm.Entities.Incident>("KnowledgeBaseRecord_Incident", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Incident");
				this.SetRelatedEntities<DLaB.Xrm.Entities.Incident>("KnowledgeBaseRecord_Incident", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Incident");
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_createdby")]
		public DLaB.Xrm.Entities.SystemUser lk_KnowledgeBaseRecord_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_KnowledgeBaseRecord_createdby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_createdby", null, value);
				this.OnPropertyChanged("lk_KnowledgeBaseRecord_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_createdonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_KnowledgeBaseRecord_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_KnowledgeBaseRecord_createdonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_KnowledgeBaseRecord_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_modifiedby")]
		public DLaB.Xrm.Entities.SystemUser lk_KnowledgeBaseRecord_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_KnowledgeBaseRecord_modifiedby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_modifiedby", null, value);
				this.OnPropertyChanged("lk_KnowledgeBaseRecord_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_modifiedonbehalfby")]
		public DLaB.Xrm.Entities.SystemUser lk_KnowledgeBaseRecord_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_KnowledgeBaseRecord_modifiedonbehalfby");
				this.SetRelatedEntity<DLaB.Xrm.Entities.SystemUser>("lk_KnowledgeBaseRecord_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_KnowledgeBaseRecord_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 organization_KnowledgeBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_KnowledgeBaseRecord")]
		public DLaB.Xrm.Entities.Organization organization_KnowledgeBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.Organization>("organization_KnowledgeBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_KnowledgeBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_KnowledgeBaseRecord")]
		public DLaB.Xrm.Entities.TransactionCurrency TransactionCurrency_KnowledgeBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DLaB.Xrm.Entities.TransactionCurrency>("TransactionCurrency_KnowledgeBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrency_KnowledgeBaseRecord");
				this.SetRelatedEntity<DLaB.Xrm.Entities.TransactionCurrency>("TransactionCurrency_KnowledgeBaseRecord", null, value);
				this.OnPropertyChanged("TransactionCurrency_KnowledgeBaseRecord");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public KnowledgeBaseRecord(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["knowledgebaserecordid"] = base.Id;
                        break;
                    case "knowledgebaserecordid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}